version: "3"

services:
  scheduler:
    container_name: "scheduler"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9091:9091
    networks:
      - app_network
    env_file:
      - .env
networks:
  app_network:
    external: true
